### ISSUE TITLE
[Bug]: Krypton Context Menu Exception

### ISSUE THREAD

**Issue by sdreb3421** [Krypton-Suite/Standard-Toolkit#1034]
When moving mouse over krypton context menu sub menu I get the following exception. This is not present in Canary 80.23.2.51 and appeared in Canary 80.23.3.79.

Object reference not set to an instance of an object.
at Krypton.Toolkit.ViewDrawMenuItem.ShowSubMenu(Boolean keyboardActivated)
at Krypton.Toolkit.MenuItemController.MouseDown(Control c, Point pt, MouseButtons button)
at Krypton.Toolkit.ViewBase.MouseDown(Point pt, MouseButtons button)
at Krypton.Toolkit.ViewBase.MouseDown(Point pt, MouseButtons button)
at Krypton.Toolkit.ViewBase.MouseDown(Point pt, MouseButtons button)
at Krypton.Toolkit.ViewManager.MouseDown(MouseEventArgs e, Point rawPt)
at Krypton.Toolkit.VisualPopup.OnMouseDown(MouseEventArgs e)
at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
at System.Windows.Forms.ContainerControl.WndProc(Message& m)
at Krypton.Toolkit.VisualPopup.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
at Interop.User32.DispatchMessageW(MSG& msg)
at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
at System.Windows.Forms.Application.Run(Form mainForm)
at MotionView.Program.Main(String[] args) in C:\Users\sethd\Documents\TFS\MotionView\MotionView\MotionView\Program.cs:line 18

**Comment by sdreb3421** [comment]
@Wagnerp Thought I'd check this one too, but this one is NOT fixed on nightly 80.23.6.168.

**Comment by Wagnerp** [comment]
More nullability checking

**Comment by Wagnerp** [comment]
Fixed 06/07/2023
