### ISSUE TITLE
[Bug]: Whilst investigating #1152 found that "Start drag" in certain application causes an exception

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1153]
Using latest alpha branches:
Whilst investigating #1152 found that "Start drag" in certain application causes an exception
Using the Docking examples:

![DockDragException](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/2809dd6e-136a-4783-82d5-14f3e03c9278)

Exception text:
``` txt
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Cannot perform operation with a page that is already present inside docking hierarchy
Parameter name: pages
   at Krypton.Docking.DockingElement.DemandPagesNotBePresent(KryptonPage[] pages) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Docking\Elements Base\DockingElement.cs:line 571
   at Krypton.Docking.KryptonDockingSpace.Append(KryptonPage[] pages) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Docking\Elements Impl\KryptonDockingSpace.cs:line 61
   at Krypton.Docking.KryptonDockingManager.DoDragDrop(Point screenPoint, Point elementOffset, Control c, KryptonPageCollection pages) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Docking\Elements Impl\KryptonDockingManager.cs:line 3167
   at Krypton.Docking.KryptonDockingDockspace.OnDockspaceBeforePageDrag(Object sender, PageDragCancelEventArgs e) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Docking\Elements Impl\KryptonDockingDockspace.cs:line 505
   at Krypton.Workspace.KryptonWorkspace.OnBeforePageDrag(PageDragCancelEventArgs de) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Workspace\Controls Workspace\KryptonWorkspace.cs:line 2700
   at Krypton.Workspace.KryptonWorkspace.InternalPageDragStart(Object sender, KryptonNavigator navigator, PageDragCancelEventArgs e) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Workspace\Controls Workspace\KryptonWorkspace.cs:line 2882
   at Krypton.Workspace.CellPageNotify.PageDragStart(Object sender, KryptonNavigator navigator, PageDragCancelEventArgs e) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Workspace\General\CellPageNotify.cs:line 40
   at Krypton.Navigator.KryptonNavigator.InternalDragStart(DragStartEventCancelArgs e, KryptonPage page) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Navigator\Controls Navigator\KryptonNavigator.cs:line 2068
   at Krypton.Navigator.ViewBuilderHeaderBarTabGroup.OnDragStart(Object sender, DragStartEventCancelArgs e) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Navigator\View Builder\ViewBuilderHeaderBarTabGroup.cs:line 613
   at Krypton.Navigator.DragViewController.OnDragStart(Point mousePt, Point offset, Control c) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Navigator\Controller\DragViewController.cs:line 418
   at Krypton.Navigator.DragViewController.MouseMove(Control c, Point pt) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Navigator\Controller\DragViewController.cs:line 135
   at Krypton.Toolkit.ViewBase.MouseMove(Point pt) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\View Base\ViewBase.cs:line 523
   at Krypton.Toolkit.ViewBase.MouseMove(Point pt) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\View Base\ViewBase.cs:line 528
   at Krypton.Toolkit.ViewManager.MouseMove(MouseEventArgs e, Point rawPt) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\View Base\ViewManager.cs:line 458
   at Krypton.Toolkit.VisualControlBase.OnMouseMove(MouseEventArgs e) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Visuals\VisualControlBase.cs:line 904
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Krypton.Toolkit.VisualControlBase.WndProc(Message& m) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Visuals\VisualControlBase.cs:line 1152
   at Krypton.Navigator.KryptonNavigator.WndProc(Message& m) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Navigator\Controls Navigator\KryptonNavigator.cs:line 1809
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Multi Control Docking
    Assembly Version: 6.0.2108.0
    Win32 Version: 6.0.2108.0
    CodeBase: file:///Z:/GitHub/Krypton-Suite/Standard-Toolkit-Demos/Binaries/Krypton%20Demos/Debug/net48/Multi%20Control%20Docking.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9172.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Krypton.Toolkit
    Assembly Version: 80.23.10.295
    Win32 Version: 80.23.10.295
    CodeBase: file:///Z:/GitHub/Krypton-Suite/Standard-Toolkit-Demos/Binaries/Krypton%20Demos/Debug/net48/Krypton.Toolkit.DLL
----------------------------------------
Krypton.Docking
    Assembly Version: 80.23.10.295
    Win32 Version: 80.23.10.295
    CodeBase: file:///Z:/GitHub/Krypton-Suite/Standard-Toolkit-Demos/Binaries/Krypton%20Demos/Debug/net48/Krypton.Docking.DLL
----------------------------------------
Krypton.Navigator
    Assembly Version: 80.23.10.295
    Win32 Version: 80.23.10.295
    CodeBase: file:///Z:/GitHub/Krypton-Suite/Standard-Toolkit-Demos/Binaries/Krypton%20Demos/Debug/net48/Krypton.Navigator.DLL
----------------------------------------
Krypton.Workspace
    Assembly Version: 80.23.10.295
    Win32 Version: 80.23.10.295
    CodeBase: file:///Z:/GitHub/Krypton-Suite/Standard-Toolkit-Demos/Binaries/Krypton%20Demos/Debug/net48/Krypton.Workspace.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Smurf-IV** [comment]
Nuget canary versions;
- ![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/d5dc96b4-3982-446b-b701-0118b4a5cbbd) - OK
- 80.23.1.23-beta - ok
- 80.23.2.51-beata = **FAILURE** is present

**Comment by Smurf-IV** [comment]
Nightly versions:
- 80.23.1.24-alpha - OK
- 80.23.1.25-alpha - OK
- etc.
- - 80.23.2.44-alpha- OK
- 80.23.2.44-alpha  = **FAILURE** is present

**Comment by Smurf-IV** [comment]
@Wagnerp Seems like the possible timeline for the changes has become mangled in Git:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/c349a6a0-ccc2-419b-8b54-45fd6943f9b3)
 By my reckoning: Build 40 should be the 9th of Feb, and 44 Should be the 13th.
 Q: Is Git tagged for these builds ?
 Q2: If not, can it be? So that if this sort of thing crops up again (I'm sure it will) it will be easier to get a timeline comparison.

**Comment by Wagnerp** [comment]
@Smurf-IV Does [this](https://github.com/Krypton-Suite/Standard-Toolkit/commits/alpha?after=c7a4f8058a15126dfadea1d1f00a690742fc7e25+419&branch=alpha&qualified_name=refs%2Fheads%2Falpha) help?

**Comment by Wagnerp** [comment]
I'll look into tagging for NuGet

**Comment by Smurf-IV** [comment]
Tracked it down to a "Deliberate" passing of nulls for https://github.com/Krypton-Suite/Standard-Toolkit/pull/1158/commits/c7e26a08c13ca87409bf7e9e2d34fe57acd6cbc6#diff-0ca48a2588f5ccffd57369100e001e05a117cb4e0d80fb4a96f64400e500bb40
