### ISSUE TITLE
[Bug]:  KryptonFolderBrowserDialog display and runtime errors [alpha]

### ISSUE THREAD

**Issue by tobitege** [Krypton-Suite/Standard-Toolkit#1351]
## Bug

- [x] In alpha branch the right bottom selection box shows an "\n" in the text, but not in master (net48).

- [x] For net7.0 or net8.0 there is no compiled executable for below demo, though there are several for other demos?

- [x] The net6.0 version of the compiled demo raises exception opening the dialog upon button click:
```
************** Exception text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Krypton.Toolkit.ShellBrowserDialogTFM.ShowActualDialog(IWin32Window owner) in D:\github\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\ShellDialogs\ShellBrowserDialogTFM.cs:line 61
   at Krypton.Toolkit.ShellDialogWrapper.ShowDialog(IWin32Window owner) in D:\github\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\ShellDialogs\ShellDialogWrapper.cs:line 52
   at Krypton.Toolkit.KryptonFolderBrowserDialog.ShowActualDialog(IWin32Window owner) in D:\github\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Toolkit\KryptonFolderBrowserDialog.cs:line 30
   at Krypton.Toolkit.ShellDialogWrapper.ShowDialog(IWin32Window owner) in D:\github\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\ShellDialogs\ShellDialogWrapper.cs:line 52
   at KryptonFolderBrowserDialog_Example_2019.Form1.ButtonShowFileDialog_Click(Object sender, EventArgs e) in D:\github\Standard-Toolkit-Demos\Source\Krypton Toolkit Examples\KryptonFolderBrowserDialog Example\Form1.cs:line 22
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at Krypton.Toolkit.KryptonButton.OnClick(EventArgs e) in D:\github\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Toolkit\KryptonButton.cs:line 636
   at Krypton.Toolkit.KryptonButton.OnButtonClick(Object sender, MouseEventArgs e) in D:\github\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Toolkit\KryptonButton.cs:line 930
   at Krypton.Toolkit.ButtonController.OnClick(MouseEventArgs e) in D:\github\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controller\ButtonController.cs:line 892
   at Krypton.Toolkit.ButtonController.MouseUp(Control c, Point pt, MouseButtons button) in D:\github\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controller\ButtonController.cs:line 410
   at Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button) in D:\github\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\View Base\ViewBase.cs:line 562
   at Krypton.Toolkit.ViewBase.MouseUp(Point pt, MouseButtons button) in D:\github\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\View Base\ViewBase.cs:line 567
```

### **To Reproduce**
- Open the demo for KryptonFolderBrowserDialog without making any changes in VS2022.  
- Compile for alpha and/or master.  
- Run the executable demo from the desired Binaries\Krypton Demos\Debug\(net version) subfolder.  
- Do not make any changes to options on the demo form.  
- Click the button "Folder Browser Dialog" button in the demo app.  

### **Expected behavior**
Text of combobox should be without "\n". No exceptions across .net versions.

### *Screenshots*
The net48 version on my German system shows this:
![grafik](https://github.com/Krypton-Suite/Standard-Toolkit-Demos/assets/10787084/91e4f686-6b4f-405d-956f-1a2406b8b164)

### **Desktop:**
 - OS: Win11 2Hxx (current)
 - Version latest alpha

**Additional context**
VS 2022, German Windows

**Comment by Smurf-IV** [comment]
In .net 6 onwards:
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/9c15586a-6bb8-4490-8d39-e15f169a2ccd)

**Comment by Smurf-IV** [comment]
- Detect if the Reflection returned a null and attempt to get the net core `-Options` instead
- Hide the Unused fields in the Folder browsing experience
- Attempt to reduce flickering (Some not all !)
![image](https://github.com/Krypton-Suite/Standard-Toolkit/assets/2418812/101419d2-d039-4be3-b823-03fdbdf3cbfa)
