### ISSUE TITLE
[Bug]: KryptonRibbonGroupThemeCombobox causes an exception when the constructor is not fully completed

### ISSUE THREAD

**Issue by Smurf-IV** [Krypton-Suite/Standard-Toolkit#1685]
Using today's alpha:
![image](https://github.com/user-attachments/assets/71a5425d-b39e-4c5a-95d6-7fc5f07c10df)

```
---------------------------
Exception Caught
---------------------------
An unexpected error has occurred:

Class: Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Rendering\ThemeManager.cs
Method: ApplyGlobalTheme
Line: 75
Message: Object reference not set to an instance of an object.

Stacktrace:
   at Krypton.Ribbon.KryptonRibbonGroupComboBox.get_SelectedIndex() in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Ribbon\Group Contents\KryptonRibbonGroupComboBox.cs:line 755
   at Krypton.Ribbon.KryptonRibbonGroupThemeComboBox.KryptonManagerGlobalPaletteChanged(Object sender, EventArgs e) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Ribbon\Group Contents\KryptonRibbonGroupThemeComboBox.cs:line 104
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Krypton.Toolkit.KryptonManager.OnGlobalPaletteChanged(EventArgs e) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Toolkit\KryptonManager.cs:line 1048
   at Krypton.Toolkit.KryptonManager.set_GlobalPaletteMode(PaletteMode value) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Controls Toolkit\KryptonManager.cs:line 259
   at Krypton.Toolkit.ThemeManager.ApplyGlobalTheme(KryptonManager manager, PaletteMode paletteMode) in Z:\GitHub\Krypton-Suite\Standard-Toolkit\Source\Krypton Components\Krypton.Toolkit\Rendering\ThemeManager.cs:line 71

---------------------------
O&K   
---------------------------
```

**Comment by giduac** [comment]
@Smurf-IV 
Works normal here on a fresh branch from current alpha.

**Comment by Smurf-IV** [comment]
> @Smurf-IV Works normal here on a fresh branch from current alpha.

It was the first thing I clicked, had you clicked on anything else ?

**Comment by giduac** [comment]
nope.
fresh branch, f5 click that button

**Comment by Smurf-IV** [comment]
Hmm..
![image](https://github.com/user-attachments/assets/d960ff83-9155-4184-9185-09f1a70b58e3)
![image](https://github.com/user-attachments/assets/33ea8fb1-f6a7-4970-91e5-0619595da036)

It's when the "MS 365 Dark is selected "BEFORE" going into the "Old style"
This can be seen just selecting it in the "Start Page" as well

**Comment by giduac** [comment]
Cant replicate that here. Tried all 365 black themes

**Comment by giduac** [comment]
Is there an inner exception?

**Comment by Smurf-IV** [comment]
@giduac Thanks for "Sticking with this"
I can confirm if you only do that with going into Control Test First.
-Open TestForm app
- Click Controls test
- Change Theme
- Close Controls test
- Then either:
  - Change them in the parent combo
  - Or attempt to open "Old Style" As per following video
 
![ThemeOrdering](https://github.com/user-attachments/assets/3e078b27-99ea-4390-886c-99c2dcca6c15)

**Comment by giduac** [comment]
now i got it too

**Comment by Smurf-IV** [comment]
> Is there an inner exception?

Member field `ComboBox` is null.

**Comment by giduac** [comment]
if you do controls test
change the theme there
then close
reopen controls test, it crashes also

**Comment by giduac** [comment]
so not related too old main

**Comment by giduac** [comment]
Found it, 

`KryptonManager.GlobalPaletteChanged += KryptonManagerGlobalPaletteChanged;`
Gets fired while the object is not fully instantiated.

Moving this hook to a OnHandleCreated routine fixes the problem.

All three Theme Selectors will receive this alteration
pr incoming...

**Comment by giduac** [comment]
RibbonGroup Theme switcher is derived from component and does not expose the OnHandleCreated method.
Here a different approach has been applied.
