### ISSUE TITLE
[BUG]: Cannot place KryptonStatusStrip on a Form

### ISSUE THREAD

**Issue by DX94-Quas** [Krypton-Suite/Standard-Toolkit#9]
**Describe the bug**
Trying to place a KryptonStatusStrip in a Form fails with the error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at ComponentFactory.Kripton.Toolkit.KryptonStatusStrip.OnRendererChanged(EventArgs e)
at System.Windows.Forms.ToolStrip.set_Renderer(ToolStripRenderer value)
at System.Windows.Forms.ToolStrip.set_RendererMode(ToolStripRendererMode value)
at System.Windows.Forms.StatusStrip..ctor()
at ComponentFactory.Krypton.Toolkit.KryptonStatusStrip..ctor()
```

**To Reproduce**
1. Create blank Windows Forms project
2. Install Krypton.Toolkit via NuGet
3. Drag KryptonStatusStrip to Form

If there is any additional info you need please ask
NuGet installed Krypton.Toolkit version 5.500.2005
**EDIT:** added Toolkit version

**Comment by Wagnerp** [comment]
Hi @DX94-Quas 

Thanks for posing your issue. It's a known bug & will be fixed in build 2006.
